#+setupfile: ../setup.org

#+hugo_bundle: train-the-mind
#+export_file_name: index

#+title: 正念，冥想与内心的平静
#+date: <2021-04-28 三 17:00>
#+hugo_categories: Mind
#+hugo_tags: mind self meditation
#+hugo_custom_front_matter: :featured_image images/featured.jpg

本文是一篇读书总结（和摘抄），阅读以下书籍与视频有感而作，
- [[https://book.douban.com/subject/34888157/][《十分钟冥想》]]
- [[https://book.douban.com/subject/26910859/][《冥想》]]
- [[https://book.douban.com/subject/24758481/][《当下的力量》]]
- [[https://www.bilibili.com/video/av39190026/][TED 分享，每天冥想10分钟，让焦虑不再]]
- [[https://www.bilibili.com/video/BV1ha4y1Y7Pd][科比采访，睡眠及冥想的奥秘]]

#+begin_quote
只有开始实践，冥想才有价值
#+end_quote

多数人的生活状态是，不断被大大小小的想法和感受所困扰，不断挑剔和评判自己以及他人。
人们如此忙于填满所有的时间，以至于失去了平静和安定的心灵。
正念可能是解决上述问题的一种方法。

具体而言，正念指的是愿意在自然觉醒状态下安定下来的意愿，它抗拒诱惑，拒绝对出现的
任何情感做出评判，并因此既不反对某种情感，也不会被某种情感所冲散。
冥想仅仅是一种练习，它为练习保持正念提供最佳条件。

在冥想中，需要创建和保持的不是某种人为的或者暂时的心理状态，
相反地，顺其自然，让心灵在自然状态下安定下来，免受日常杂务的干扰。
这就是心灵训练的意旨。

心灵训练有三个要素，
1. 理解冥想技法，了解在实践这种技法时心灵可能会如何表现。
2. 练习冥想。
3. 保持正念。在对冥想技法有了一定程度的熟悉之后，
   将心灵的这种特性整合融入日常生活。

* 理解

内心的想法是自发的，而且没有什么外力能够阻止它们的出现。

前一分钟你还在读书，后一分钟关于某个老朋友
的想法“突然出现在”你的脑海中。
你很久没想起过这个老朋友了，你并未有意
识地把他带到你的脑海中，然而突然之间，他就在那里了。
这些我们非常努力想要压制、想要去除、想要完全制止的想法，
很大程度上是突然自动出现的。

我们倾向于觉得自己控制着大脑，控制
着思维的转换，
事实上，如果你无法控制自己的想法。
如果可以，你就会阻挡住所有那些令人不快的想法，与
所有那些令你开心的想法和平共处。

冥想不是去阻止想法、控制心灵，它是一个过程。
在这个过程中，我们放弃控制，
不插手，不介入，学会以被动的方式集中注意力，
同时将心灵安放在它自有的，自然的觉醒中。

下面引用几个隐喻，来尝试理解，冥想时的状态是什么。

** 道路

想象自己坐在繁忙的路边，而眼罩蒙住了你的双眼。
也许你可以听到周遭的噪声，听到汽车嗖嗖驶去的
声音，但是你看不到，因为你的眼睛被遮住了。
在你开始冥想之前，感觉会跟这个场景有点相似。
因为心灵充斥着噪声和各种想法，所以哪怕在你坐下来开始放松，
或者晚上上床睡觉的时候，你仍然会觉得这种噪声萦绕在耳旁。

想象一下把眼罩摘掉，你第一次清楚地看到这条
“路”，也就是你的心灵。
你看到车子飞驰而过，看到不同的颜色、形状和尺寸。
也许有时候你会被汽车的声音所吸引，而有的时候又会对它们的外观更感兴趣，
这就是你最初摘掉眼罩时的状态。

*你要明白的第一件事是，冥想不是思考！*
它所做的不过是将一道明亮的
光照耀在你的心灵上，所以你才更清楚地看到一切。
你也许不喜欢灯光打开时你所看到的东西，但是冥想会清晰而准确地反映你的心灵
每天都在做的事情。

当你意识到心灵的这种混乱状态的时候，你很难
知道该对它做些什么。
有些人难免会惊慌失措。有时候，人们会试图通过外力阻
止这些想法，而有的时候，他们会试着忽略它们，去想些别的事情。
或者，如果
这些想法很有趣，他们也许会努力助长它们，并参与其中。事实上，所有这些都
不过是竭力逃避现实的方法而已。回想到刚才那条繁忙的路，这种做法无异于从
路边站起来，在车子间跑来跑去，试图控制交通。
这是一种相当危险的策略。

何不在你原来的地方待一会儿呢？
不要在车子中间跑来跑去，试图控制一切。
如果你只待在路边，
只看着车来车往。
也许当时正是上班高峰期，路上满是车辆；也许当
时正值午夜，路上没几辆车。无论是哪种状态，其实并不重要。重要的是，你要
习惯于停留在路边，坐看车来车往。

当你退后一
步，与这些想法和感受保持距离时，你会有种豁朗感。你也许会感觉好像你不过
就是一个观察者，观看这些想法（车辆）来了又去。

有时候，也许你看着看着就
忘了，
当你觉察到这点的时候，你早已跟着一辆漂亮的车顺着路跑
下去了。当你感受到一个令人愉快的想法时，你看到了它，对它入了迷，最后跟
着它走了。
然后突然
之间，你意识到自己在做什么，就在那时，你便有机会重新回到路边坐着。
有的
时候，你也许会看到有你不喜欢的车过来，也许是一辆生锈的旧车（令人不快的
想法）。你无疑会冲过去，跑到路上，想要阻止它，你也许会竭力抗拒这种感受
或想法。
就在你意识到要回去的那一刻，你就有了再回到路边的机会。

随着时间推移，这个过程会变得更加容易。你不
会再频繁地跑到路上，你会发现自己越来越容易安心地坐在路边，观察着想法来
了又去。
*这就是冥想的过程。*

** 蓝色天空

把你的心灵想象成一片蓝色的天空。
这就像是心灵的深层实质，以及自然的状态。

偶尔会有布满阴云的日子，没有蓝色的天空，只有
大片阴沉沉的云。
设想这些云就是你心里的想法，它们有时候蓬松柔软、洁白无瑕，看起来非
常令人愉快，然而有时候，它们又是那样阴沉黑暗。

如果你从那些云的一端穿过，另一端就没有阴云，而只有蓝色的天空了。
就算有大片阴沉沉的乌云，蓝色的天空也始终存在。

*天空总是蓝的。*

云相当于我们的思想，当心灵忙于这些想法的时候，蓝色的天空就
暂时被遮蔽了。
我们的心灵一直如此忙于各种想法，忙碌的
时间又如此之长，以至于我们几乎忘了蓝色的天空到底是什么样了。
无论感受如何，心灵的深层本质就像蓝色的天空一样，
并没有发生变化。当我们因为某种原因心情不好或者感到痛苦的时候，云会变得
更加阴沉，更令人烦扰。

冥想不是需要努力去创造一种人为的心境，
不是努力把阴云赶走，而是搬把椅子到花园里，
坐看云卷云舒。
有时候，蓝色的天空会穿过阴云展露出来，令人备感美好。

如果你能耐心地坐在那里，不过分执着于那些阴云，那么蓝色的天空会显露得更
多。一切都好像是自发产生的，并不需要做任何事情。
不挣扎，不干涉，顺其自然。

** 野马

设想你抓住了一匹野马，想把它关在某个地方。
没有哪个人能控制住一匹野马，它太强壮了。
就算你跟你所有的朋友一起努力，你们也永远不可能把它控制在一个地方。
这不是驯服野马的方式。

在你最初抓住这样的一匹马的时候，你需
要记住，它们习惯了自由奔跑。它们不习惯静静地长久站在一个地方。

在你坐着冥想的时候，你的心灵就像这匹野马，
你不可能因为你像一座雕像一样坐在那里做某种叫冥想的事，就指望它突然静
静地在某个地方站定！因此，当你跟这匹野马，也就是你的心灵，一起坐下来的
时候，你需要给它提供很大的空间。不要试图立刻将注意力集中在冥想对象上，
相反，要给你的心灵一点时间，让它安定下来。

你要像训练野马那样去靠近你的心灵，要想象自己站在一个非常大的空间
的中央，即一块开放田野的中央。现在，缰绳的一端系着这匹马，另一端在你手
里。

缰绳是松弛的，这匹马有它所需要的一切空间，它并没有觉得被困住
或者受到约束。
现在，非常缓慢地一点点收回绳子，从而缩短绳子的长度。

如果你对一匹野马做这样轻柔缓慢的动作，它就根本不
会注意到，它会仍然觉得自己好像拥有广阔的天地。继续这样做，一点点地把马
带到自己身边，同时密切地观察它，但是要给它足够的空间，让它感到自在，不
要让它太紧张。

这就是你坐下来发现心灵非常繁忙时需要做的事情。
慢慢来，缓缓地，给它所需要的空间。
让野马进入自然的安定空间，进入令它感到喜悦、自信、可以放松停留
的地方。它可能刚开始的时候会有点挣扎，但是没关系，再把绳子一点点地放松
些，慢慢地重复这个过程。

*如果你以这种方式进行冥想，那么你的心灵会非常喜悦。*

** 剧院

设想一下，你正在观看一个舞台剧。

指挥表演不是你的职责，跑到舞台上、介入正在展开的故
事也不是你该干的事。
舞台上演着的可能是个浪漫爱情剧，也可能是冒险动作剧，
还可能是神秘情节剧。
这个剧可能节奏很快，让你
没有喘气的空儿，也可能节奏沉稳、令人放松而自在。

重点在于，无论发生了什
么，你唯一的职责就是观看下去。
刚开始的时候，这也许很容易，但是也许故事
进展太缓慢，你开始焦躁不安。
也许你会四下张望，看看别的东西来聊以自娱，
或者你会思考第二天需要做的事情。
在这个时间点上，你完全没有觉察到舞台上到底发生了什么。
一旦意识到自己心灵游离，你的心神就立刻又回到舞台上，你又开始观看。
如果你分心走神了，那就不是冥想了。
只有在你不分心不走神的时候，才是冥想。

你坐在那里冥想的情景跟观看这部剧的情景有点相似。
那些影像和声音不是来自
你，同样地，剧中或电影中的影像和声音也不是来自你。
那不过是你正在观看、
观察和目睹的正在展开的故事。

*这就是我们要说的觉醒。*

在你自己的人生中，你自己的故事，需要你去指引方向，需要你去鼓励，
但是冥想期间，坐在那里观察心灵的时候，
拿把椅子去观众席上坐着是迄今为止最好的观察方式。
只有在培养出了这种被动的观察能力之后，你才能体验到澄澈。
觉醒不是需要你去创造东西，而是觉察一直都在的东西。

* 十分钟冥想
   
** 概要

*** 预备

1. 找个地方，舒适地坐下来，腰背挺直。
2. 确保在冥想期间，不会受到人或事的打扰。
3. 设好 10 分钟的闹铃。

*** 签到

1. 做 5 次深呼吸，用鼻子吸气，再用嘴巴呼气，然后轻轻地闭上眼睛。
2. 将注意力集中在身体落座时的躯体感觉，脚放在地板上时的躯体感觉上。
3. 扫描全身，留意身体哪些部位感到舒适和放松，哪些部位感到不适和紧张。
4. 留意自己的情感，比如，你现在处于什么心情。

*** 专注于呼吸

1. 留意你在哪个部位最强烈地感受到呼吸时的起伏感觉。
2. 留意每次呼吸所带来的感受，注意每次呼吸的节奏，无论是长还是短，是深还
是浅，是粗重还是顺畅。
3. 在将注意力集中到起伏感觉上时，缓缓地数一下呼吸次数，吸一次气数 1，呼
一次气数 2，一直数到 10。
4. 重复这个过程，循环 5～10 次，或者如果时间允许，可以一直循环下去。

*** 结束

1. 注意力不再集中，任由心灵随心所欲地忙碌或放松 20 秒。
2. 将心灵带回到躯体感觉上来，即身体在椅子上的感觉，脚放在地板上的感觉。
3. 在准备好之后，缓缓地睁开眼睛，站起来。

** 解释

*** 预备

这一部分是让你以正确的方式为冥想做好准备。
你会惊讶于竟然会有许多人像疯
了一样冲过来，然后快速坐下来闭上眼睛，等着心灵安静下来。那怎么可能会起
作用呢？
如果之前你的心灵很繁忙，那么在你坐下来冥想的时候，它会需要很长
时间才能安静下来。

可能的话，提前 5～10 分钟让心灵慢下来，这样你开始练习冥想的时候心情状态
会正好合适。
确保你用闹铃定好了时间，确保在接下来的 10 分钟里没有人或事能
打扰你。

虽然学习冥想的时候最好是腰背挺直坐在椅子上，但是你也许更想躺下
来。虽然躺下这个主意颇具诱惑力，但是身体躺下后，你会很难在专注和放松之
间实现平衡，而且你也许会在不知不觉中迷迷糊糊地睡着。
如果你非要躺下来，
请一定躺到坚硬的平面上去，把胳膊和腿伸开绷直。你还可以在膝盖下面放一个
枕头，以便减轻后背下部的压力。

*** 签到

这个阶段旨在身心合一。
想一想，你是不是经常身体在做一件事，而心灵却在干
别的事情，处于游离状态？
也许你正沿街走着，但是你的心已经在家里，在计划
着晚餐，或者在想电视上正在播放什么节目。我们其实很少能做到身心的时空合
一。因此，这是一个机会，这个机会让你在自己所处的环境中安顿下来，让你清
醒地觉察到自己在做什么，意识到自己在哪里。

在理想状态下，应该花 5 分钟左右的时间来“签到”。随着你对整个过程越来越
熟悉、越来越熟练，后面你可能觉得不需要这么长时间，但是在这方面也还是不
要着急，这一点很重要。
有些人做“签到”的时候，会有一种想法，觉得这只是
一种可有可无的准备，而不属于真正的练习。他们可能会想：“算了，不要做这
个了，我要开始做真正的冥想，把注意力集中在我的呼吸上，让疯狂的心慢下
来。”但是心灵的运作方式不是这样的。
回想一下野马那个类比，在刚开始的时
候要给它所需要的一切空间，而不是立刻将它约束在一个地方。签到其实就是将
那匹马带到一个自然的安静之地。

从睁着眼睛开始，你不要一直盯着某个特定的事物，而要柔和地看着前方，把外
围的影像也兼顾到，上方、下方，以及两边。

然后，你需要做 5 次深呼吸，用鼻
子吸气，再用嘴巴呼气。在你吸气的时候，注意体验肺部充满空气的感觉和胸腔
扩展的感觉。在你呼气的时候，任由气体出去，想象自己卸下了一直以来紧紧持
有的紧张或压力。
在你第 5 次呼气的时候，可以轻轻地垂下眼皮，然后任由呼吸
回到自然状态，用鼻子吸气，用鼻子呼气。

在闭上眼睛的时候，你会立刻更敏锐地体察到躯体感觉，会更能体察到自己坐着
的姿势。
你弯腰了吗？你的手和胳膊完全压在腿上吗？这是你在进入正式练习之
前调整这些姿态的好机会。接下来，将你的注意力集中到你身下的椅子给你带来
的躯体感觉上，集中到身体重量压在椅子上的那种感觉上。这是你的身体和椅子
之间的联系感。注意你的重量是通过你身体的中间部位均匀地压在椅子上，还是
更多地压在某一边。现在，你要对脚做同样的事情，注意脚底和地板之间的接触
感。接触感最强烈的部位在哪里，是脚跟、脚趾、脚的内侧，还是外侧？你需要
在这里停顿一下，时间要足够长，直到弄清楚这种感觉。最后一点，你要对手和
胳膊重复这个过程，感受重力的作用，感受胳膊压在腿上的重量，感受手和腿之
间的接触。你不一定得对之做些什么，只要能察觉到就足够了。将你的注意力从
一种感觉转到另一种感觉，记住，做的时候带一点适度的好奇心。

在这样做的时候，毫无疑问，会有很多想法跳进你的脑中。
这是非常正常的，你
不需要做任何事情去试图改变这种状况。它们不过就是些想法而已。
回想
“道路”那个比喻，我们的理念是，不要试图去阻止想法，而要顺其自然，任由
想法在你完全觉醒的状态下来来去去。此外，在这个时候，我们要把注意力集中
到我们的躯体感觉上，而不要集中到任何想法或情感上，这样你才能任由这些想
法在幕后来了又去。

花一点儿时间，留意一下任何声音。这些声音可能离你非常近，或者在另一个房
间里，甚至可能在楼外面。它可能是汽车驶过的声音、人们交谈的声音、空调的
声音。重要的不是这些声音是什么，而是任由它们来去。有时候，你也许会捕捉
到自己“参与”到了某个声音中去，或者在聆听某个对话。这都是很正常的，事
实上，一旦你意识到自己沉溺于某个特定的声音，你就会开始注意到其他所有细
小的声音。如果你住在繁忙的都市里，那么你可能常常会把外在的声音当成冥想
修习的障碍，当作妨碍你产生宁静心灵的东西。但是，事情不一定非得是那个样
子。首先，如果你能找到一个安静的房间坐下来，那当然很理想。如果你能有意
识地努力承认这些声音，而不是抗拒它们，就会有很有趣的事情发生。喜欢的话，
你还可以用自己的其他感官重复这个过程，比如，留意所有强烈的味道，甚至品
尝嘴里的东西。这样，心灵会参与到躯体感觉中去。

其次，了解身体的感受。你先大体了解身体各部分的紧张或放松情况。在这个阶
段，我们要做的不是改变任何哪种感受，而是做一个了解。第一遍的扫描可能只
需要大约10秒的时间。这一步就类似于先从外面去打量一座房子。接下来，你需
要进入房子，对房子的状况有更细致的了解。为了做到这一点，你需要花大约 30
秒的时间，从上到下对身体进行“扫描”（从头顶开始，一直到脚尖），留意身
体各个部位的感受。
哪一部位感到舒适？哪一部位感到不适？紧张的部位在哪里？
放松的部位又在哪里？在这样做的时候，你也许会很想将局部放大，只关注那些
紧张部位。事实上，有时候你甚至会觉得，好像全身除紧张之外，就没有别的感
觉了！但是，请你尽可能系统地扫描全身，既留意舒适感，也留意不适感，不要
忘了留意你的手指、脚趾和耳朵带给你的感受。

在扫描的时候，你也许会更为觉察自己的想法和感受，即便你并没有对它们加以
特别关注，任由它们来去。一旦意识到自己分心走神，意识到心灵游离，你只需
要温和地将注意力带回来，带回到身体扫描上来，带回到中断的地方来。这是很
正常的，而且很可能会发生很多次，因此，没什么可担心的。如果你真的注意到
了某种特别强烈的情感特质，只需承认它就足以起到作用。

我们常常执迷于自己的想法，忙于一天中的活动，以至于常常觉察不到自己的情
感。这也许听起来好像不要紧，但是如果你能觉察到自己的感受，那么你就能对
这种情感做出反应。如果你连觉察都觉察不到，你就很可能会发现自己在一天中
的某些时段在冲动性地做出反应。
我们都见过这种场景，温和的商人或家庭主妇，
原本看起来很适应环境，平静地站在超市排队的队伍中，然后却突然失控。也许
是他们被手推车撞到了，也许是他们的卡在收银台那里被拒了，这些事情若是在
别的时间，他们也许根本就不会在意，但是因为那种深层的情绪，他们突然失控，
情绪大爆发。

人们常说，他们对自己的情绪完全一无所知，也没觉得有什么。然而，知道自己
一无所知也是一种知道，而且“签到”这个过程重复的次数越多，你就越会觉察
自己的深层情绪。在这个特定的练习中，我们对待情感和躯体感觉的方式是一样
的。你所觉察到的无论是一种令人愉快的舒适感，还是令人不快的不适感，这些
都不重要。在这个练习中，我们不要求对这种情感做任何分析或评判，只要留意
这种情感，承认它，并意识到它的存在就足够了。

最后，你也许会发现短暂地（这里我指的是5～10秒钟的时间）确认一下你的人
生现状会有一些用处。你可能正在为某个即将到来的事件感到激动，或者正在为
将要进行的会面感到焦虑，或者正在为与某人之间的交谈感到生气，或者正在为
自己刚收到的赞扬感到开心。无论你的现状如何，确认一下，意识到它的存在。
如果这件事最近在你的心里分量很重，那么它几乎会不可避免地在练习的某个阶
段突然出现在你的脑海中。如果你在最初的时候就对此很清楚，那么你其实就对
这些想法可以在哪里出现和消失划定了框框。你就不会再沉溺其中了。

我认为，这整个“签到”过程在刚开始的时候应该占到大约5分钟的时间，而如
果你只有5分钟时间，那么你可以只做这个练习——其重要性不言而喻。如果不完
成这个过程，那么直接专注于呼吸就不会有什么益处。因此，一定要确保认真完
成这一部分。虽然“签到”是冥想中的一部分，然而它在其他场合也有很多用处。
你可以在公交车上、在桌边，甚至在排队的时候利用它。在这些场合，你在做深
呼吸的时候可以做得更隐蔽些，而如果你正在站着，那么你可以不闭眼睛。除此
之外，你完全可以以同样的方式做这个“签到”，而且你能在心里体验到同样的
自在感。

*** 专注于呼吸

在我们把“野马”带到自然的安定之地后，它也许会继续烦躁不宁一会儿，或者
会开始感到厌烦。因此，我们需要给它一些东西，让它专注于此。正如我前面所
说，呼吸是可资利用的最容易、最灵活的东西，因此，在这个练习中，呼吸将是
首要的专注焦点。

你需先花上一小会儿时间（大约30秒）来体察呼吸，特别是气体进出身体时带来
的起伏感。最初，你只要留意身体中的哪个部位感觉最强烈，可能在腹部，也可
能在横膈膜附近，还可能在胸腔位置，甚至在肩膀位置。无论你在哪里最清晰地
感知到它，请你花上一小会儿的时间来留意呼吸起伏时带来的躯体感觉。如果呼
吸很浅，很难确定，那么你可以把手轻轻地按在腹部肚脐正下方的位置上——你也
许会发现这样很有帮助，甚至很令你安心。这样，随着你的手来回地移动，你可
以很轻易地追踪到腹部的起伏。然后，你可以把手放回到原来的位置，把手安放
在膝盖上，继续这个练习。


事实上，除非你之前已经做过放松练习或者瑜伽练
习，否则大部分情况下你可能甚至对自己的呼吸方式毫无觉察。呼吸是自发的，
是一项不需要我们控制的机能。呼吸这项机能一般能自然舒适地进行，何况它还
具备自然智能。因此，不要人为地进行控制（请你注意我们这里强调的主旨），
任由身体自己做自己的事。它会不急不躁地以自己的方式调节自身。有时候，呼
吸可能在某个地方表现得更明显一些，而当你去查看它的时候，它又转移了。有
时候，它会舒适自在地一直待在某个地方，无论这个地方是腹部、胸腔，还是介
于两者之间的某个地方。你唯一的职责就是留意它，观察它，留意身体在自然地
做什么。
记住，在这种练习
中，只有觉醒和蒙昧之分，只有没走神和走神之分，而不存在错误的呼吸或糟糕
的呼吸。

因此，你不要试图去改变呼吸的位置，而要把注意力放在呼吸这个躯体动作上，
放在身体的起伏感觉上。在这样做的时候，可以慢慢地开始注意呼吸的节奏。你
身体中的呼吸是怎样的，是快还是慢？在尝试回答之前，你需先花上几秒钟时间
体察呼吸。这些呼吸是很深，还是很浅的？你还可以注意这些呼吸是不顺畅的还
是顺畅的，是绷紧的还是放松的，让你感到温暖还是凉爽。这些问题可能听起来
很奇怪，但它们遵循的是“在冥想中带上适度的好奇心”的理念。这个过程只应
该花大约30秒时间。

在你充分了解这些躯体感觉之后，现在，把注意力集中到每次的吸气和呼气上。
这样做的最简单的方式是在一呼一吸时对呼吸进行计数（自己默默地数）。在感
受到吸气的时候数1，在感受到呼气的时候数2，以这种方式一直数到10。数到10
之后，再回到数1上，重复这个练习。这听起来比实际做起来要容易。如果你跟
我刚开始时的状态一样，你会发现，每次还没数到3或者4，你的心思就游移到其
他更有趣的事物上去了。或者，你可能会突然发现自己已经数到62、63、64了，
猛然意识到自己忘了在数到10的时候停下来。这两种情况都是非常常见的，都是
学习冥想过程中的一部分。

一旦意识到自己分心了，意识到心灵游离，你就不会再分心了。因此，你所有需
要做的就是温和地把注意力带回到呼吸时的躯体感觉上，然后继续数数。如果你
还记得自己走神前数到几，那就从那里开始接着数，而如果你不记得了，就从1
重新开始。你是不是从1重新开始数数都没关系，毕竟成功数到10，你也拿不到
什么奖励。事实上，每次都能从1数到10是很难的，这有时候让人觉得非常好笑。
如果你想笑，笑一笑也没关系。出于某些原因，冥想有时候看起来非常严肃，你
会很想把它当成“很严肃的事”。事实是，你往冥想里面带入的幽默感越多，带
入的戏谑感越多，它就越容易、越令人觉得愉快。

继续以这种方式计数，直到你设定的闹铃响起，你知道这次修习结束了。然而，
先不要从椅子上一跃而起，你还有一项很重要的事情要做。

*** 结束

这个部分常常被忽视，然而它却是练习中的重要部分。
在计数完毕的时候，让自
己的心灵完全自由下来。这意味着不要把注意力集中在呼吸上，不要把注意力集
中在计数上，不要把注意力集中在任何事物上。如果你的心灵想要忙起来，就让
它忙好了。不需要你花费任何精力，不要去控制它，不要有任何形式的审查，只
任由它完全地自由活动。我不知道这个提议会让你觉得很美妙还是很恐惧。无论
你觉得美妙还是恐惧，请任由你的心灵放松10～20秒，然后再结束冥想。有时候，
在这样做的时候，你也许会留意到脑中的想法实际上比你在努力专注于呼吸上的
时候还少。
如果你回想还没被驯服的那匹野马
的例子，你会发现，在拥有一点空间时，它常常会更舒服、更自在，这个时候它
往往也不会带来很多麻烦，但是当它被拴得有点过紧时，它往往会乱踢。因此，
如果你能把这种豁朗特质代入你在关注呼吸时所采用的技法中，那么你就会开始
见识到冥想带来的更多益处。

在任由心灵闲逛了一会儿之后，请你慢慢地将注意力收回到躯体感觉上去。这意
味着，将心灵带到躯体感觉上去。请你再一次注意身体和身体下面的椅子之间扎
实的接触感、脚底与地板之间的接触感，以及手和腿之间的接触感。花一点儿时
间，留意一切声音、一切强烈的气味或味道，慢慢地通过触及和觉察每种感觉回
归自我。这样做的作用是，将你完全带回到你所处的环境中。然后，你缓缓地睁
开眼睛，慢慢地重新适应、重新聚焦，对周围的空间保持觉醒，带着把觉醒感和
身心俱在感带到一天里剩下的时间中的打算，慢慢地从椅子上站起来。要清楚自
己接下来要去哪里、要做什么，因为这会帮助你保持那种觉醒感。也许你是要去
厨房给自己倒杯茶，也许你打算回到办公室去坐到电脑前，无论你是打算要做什
么，这些都不重要。重要的是，在你自己的心里，你要清楚，你有能力在完全觉
醒的状态下继续体验每一刻，体验一刻又一刻。

* 正念

#+begin_quote
得道前，砍柴时惦记着挑水，挑水时惦记着做饭；
得道后砍柴即砍柴，担水即担水，做饭即做饭。
#+end_quote
  
虽然需要持续不断的努力才能做到觉醒，然而正如冥想技法一样，我们所需要的
这种努力是一种不需要努力的努力。
这种努力只是记得留意自己什么时候陷入想
法或感受，以及在觉察到自己深陷其中时，调整自己的注意力，把它重新集中到
某个特殊的关注焦点上。
这个关注焦点可以是：你正在吃的食物的味道、你开门关门时胳膊的动作、
你的身体压在你身下的椅子上时你的重量、你在冲澡时水冲
到皮肤上的感觉、你在锻炼身体时心跳的声音、你和你的孩子身体接触时的触感、
你在刷牙时牙膏的味道、你拿着杯子喝水时那个简单的动作。
无论这个关注焦
点是什么，这都没关系。
你可以将觉醒应用到你所做的任何小事上，无一例外。
你可以将它应用到被动或积极的活动中，应用到户内或户外的活动中，应用到工
作或玩耍中，应用到个体活动或群体活动中。

正念意味着心在当下，意味着对自己正
在做的事情、自己身处的地方保持觉醒。
你不必改变自己平常的行事方式。
你唯一需要做的就是保持觉醒，而保持觉醒最简单的方式就是让注意力有关注的焦点。
每当你意识到心灵游移的时候，只需要将注意力带回到原来的焦点上就可以了。

在开始将这种专注方法应用到各种情形中时，你会发现，它对心灵有着很好的安
抚效果。你不仅会心神俱在地体验到自己所做的一切事情，
还会感到心平气和，而伴随着平静而来的是澄澈。你会开始看清自己的
思维方式和感受方式，并明白自己为什么会有这样的思维和感受。
你会开始注意
到心灵的活动路径和习惯，而这样做会使你获得选择权，以便选择自己的生活方
式。这样，你就不会跟着破坏性的或者无成效的想法和情感随波逐流，而是以自
己真正喜欢的方式做出回应。

正念的美好之处在于，你不需要抽出额外的时间来修习。
它所要实现的不过是训
练你的心灵，使你的心灵专注于自己的活动，而不是沉浸在其他想法中。

你应该把正念视为你可以在一整天中运用的东西，而不是只想着在每天早
上 10 分钟的冥想中保持正念，然后努力设法过完剩下的23小时50分钟，直到再次
开始冥想为止。

正念的全部意义就在于将你的全部注意力集中到你任何
时候所做的任何事情上。这种做法带来的影响是，你不可能再去想你宁愿自己在
哪里，宁愿自己在做什么，宁愿事情完全是另外一种样子，所有这些想法都会使
你紧张不安，因为你将身心集中在你所做的任何事情上。
我们中有多少人一直都是这样生活的？
沉浸在对过去的回忆和对未来的规划中，
如此全身沉浸在思考中，而完全没有意识到当前发生的事情，对周围展开的生活
浑然不觉。
当下此刻的感受是如此平常，以至于我们把它当成理所当然的事，然而事实上，
它并不寻常，毕竟我们很少在当下此刻感受过当下此刻。与人生中的
其他事物都不同的是，你不必从任何地方获取它，也不必做任何事情去创造它。
无论你在做什么，它就在这里，它就在普通平常的日常活动中，如就在你吃三明
治的动作中，就在你喝水的动作中，就在你洗碗的动作中。

*这就是正念、心在、觉醒的要义所在。*

* TODO 冥想练习

** 练习一 无为

现在你就试试，待在你现在坐着的地方，把书合上并放到你的大腿上。你不必刻
意坐到某个地方，只需轻轻闭上眼睛，静坐一两分钟。如果有很多思绪涌现出来，
没关系，任由它们来去，你要体会静坐的感觉，什么都不要做，只需一两分钟。

你感觉怎么样？也许什么也不做会让你感到特别放松；也许你会觉得需要做点儿
什么，哪怕只是在练习期间做点儿什么；也许你觉得有必要专注于某事，有以某
种方式让自己忙起来的冲动。不要担心，这不是考试，在下文中我们讲冥想的时
候，会有很多东西让你忙起来。我想哪怕在整个冥想的初始阶段，留意心中那些
总想做点儿什么的习惯或欲望，也会给你带来好处。如果你没有体会到这种想要
做点儿什么的冲动，那么你也许可以再试一次这个练习，但这一次，可以把时间
拉长一些。

我不是说看电视、听音乐、喝饮料、买东西或者跟朋友一起玩有什么不对。相反，
这些都是供我们消遣的事情。只是我们要认识到，它们帮助我们得到的只是暂时
的快乐，而不是持久的头脑空间。你有没有过这种感受，即一天的工作结束后，
因为心灵忙忙碌碌而有种恍惚的感觉？也许你决定在晚上“关掉”心灵，要看一
会儿电视节目让自己感觉好一点儿。如果节目真的很好，以至于你完全被它所吸
引，那么你也许会觉得是它让你摆脱了那些思绪，让你能休息一会儿。如果节目
无趣，或者有许多广告，那么它反倒会创造出足够的空间，使得那些想法在这些
空间里不时地起伏。无论是哪一种情况，当节目结束的时候，所有这些想法和感
受很可能都会重新席卷而来。不错，它们再回来的时候也许强度会稍弱了些，但
是它们很可能依然会隐于幕后。


大多数人的生活就是这样度过的，从一个分心物转向另一个分心物。工作的时候，
他们会太忙、太分心，而注意不到自己的真实感受，因此，当他们回到家的时候，
突然会有很多想法涌现出来。如果他们设法在晚上依旧保持忙碌，那么直到睡觉
时，他们也许才会觉察到这些想法。此时，你的头枕在枕头上，而大脑好像突然
开始超速运转。当然，这些想法一直都在那里，只是没有任何让人分心的事物，
你终于觉察到它们的存在。有些人的社交生活或者家庭生活是如此繁忙，以至于
他们要到工作的时候才会觉察到自己有多疲惫，觉察到有那么多想法在自己大脑
里横冲直撞。


所有这些分心事物都会影响到我们的专注能力，影响到我们的表现，而且使我们
无法达到最佳的生活状态。无须多言，如果心灵中总是有很多想法在横冲直撞，
我们的专注能力就会严重受损。




** 练习二 感觉

请你再抽出两分钟的时间来做一下这个小练习。跟之前一样，你坐在现在的位置上别动。你把书放到自己的大腿上，然后慢慢地把注意力集中到某种躯体感觉上，最好是听觉或者视觉上。我建议你倾听周围的声音，闭上眼睛，但是这类声音有时候有点儿难以捕捉，因此，你也许更喜欢睁着眼睛，盯着房间中的某个特定物品。无论你选择哪种感觉，试着尽可能长时间地专注于它，但是要以非常轻松、非常自在的方式。如果你被自己的想法或者其他躯体感觉分了神，只需把自己的注意力转回到你之前专注的那个物体上，一如既往。

你觉得怎么样？你是能够非常轻松地专注于这个物体上，还是发现自己的注意力
不停地偏移到其他想法上去呢？在你分神之前，你的注意力集中了多久？也许你
发现，你能够维持一点模糊的觉醒意识，同时却想着其他事物。虽然这听起来是
不太可能的事，但是对许多人来说，专注于某个物体上能维持一分钟都相当了不
起。在思考自己需要多久才能集中注意力到自己的工作、照看家人、聆听朋友心
声甚至是开车上时，一想到自己只能集中这么短的时间，你也许就会特别忧虑。

** 练习三 躯体感觉

** 练习 5 对情感保持觉醒

我们并不总是擅长辨认自己的内心感受。这通常是因为我们会被我们正在做的或
者正在思考的事情分神。当你开始冥想的时候，你不可避免地会更加清醒地感知
自己的感受——情感的种类、强度，以及情感的持久性和短暂性。比如，你现在是
什么感受？你可以把本书放下几分钟，闭上眼睛，刚开始的时候，注意一下自己
的身体有什么感受。这样做会非常有用，因为它会给你线索，让你知道你的深层
情感是什么。你觉得这种情感是沉重的，还是轻盈的？你身体中有种宁静感还是
不安感？你有没有一种局促感或者豁朗感？不要急于确定，调动你那适度的好奇
心，每个问题花上二三十秒的时间去回答。你的呼吸带给你什么体验——快还是慢，
深还是浅？不要试图去改变它，只花一点儿时间去留意一下它所带来的感觉。练
习结束的时候，你很可能会对自己的情感有更好的认识。如果没有，你也不要担
心，因为这种情况在初始阶段是很正常的，随着修习的深入，一切会变得更加明
朗。

   
** 练习6：用心灵扫描身体

为更好地培养适度的好奇心，你可以将好奇心应用到躯体感觉上。你可以将本书
放下，像以前一样轻轻地闭上眼睛，多次用心灵对身体进行全面扫描，从头顶开
始一直到脚趾尖。第一次的时候，快速扫描，花10秒的时间从头到脚尖。第二次
的时候，用时稍微长一点儿，大约20秒。然而，最后再扫描一次，花30～40秒的
时间来做。在全面扫描身体的时候，请注意身体的哪个部分感到放松、舒适、自
在，哪个部分感到疼痛、不舒服或者存在某种程度的束缚感。请你努力做到不带
任何评判或分析，而更多地带着了解身体各个部位的感受去做。如果有想法时不
时地让你分心走神，请不要担心——在注意到心灵游移的时候，你可以轻轻地把它
拉回来，回到你中断的地方去。

** 练习7：饮食冥想

   请你在餐桌旁坐下来，最好是一个人，远离所有外在的分心事物。如果有你控制不了的外在声音，也不要过于担心，因为你可以把这些纳入练习，就跟你在十分钟冥想中所做的那样。

请你在拿起食物吃之前，深呼吸几次，鼻子吸气，嘴巴呼气，让身体和心灵安顿下来。

接下来，请你花一点儿时间，欣赏食物。它们来自哪里，出自哪个国家，是自发生长出来的，还是人为制造出来的？请你试着想象一下它们生长环境中的各种要素，甚至可以想象一下照看这些庄稼或者动物的是什么人。随着时光流逝，我们已经完全与食物的来源脱了节，这也许听起来并不是很重要，然而就培养更广阔的正念饮食习惯而言，有时候这真的特别重要。

请你在这样做的时候，留意心中有没有任何不耐烦，有没有想要吃它的感觉。也许你在想所有需要你“站起来去做”的事情。无论你的反应是什么，它很可能只是条件性行为，即一种习惯而已，只不过它是一种你也许会觉得特别强大的习惯。

现在，请你花一点儿时间感恩一下，感恩你的碗里有食物可吃，不要因为你想吃它，而有愧疚感。我们有时候会忘了，在这个世界上，还有许多人没有东西可吃。你也许不愿意想这个，但是这个过程真的很重要，感谢和感恩是稳定的正念修习的中心所在。

正如我所说，接下来你也许想要做得比往常慢一些，但是无论你怎么做，请自然地做，不要想太多。

如果是要用手拿着吃的食物，请你在拿起它之后，注意它的纹理、温度以及颜色。如果食物是放在盘子里的，那么请你把餐具伸向食物的时候，留意餐具的质地和温度，并花些时间观察餐盘上的颜色。

在你将食物送进嘴里的时候，请把关注焦点从手上移开，转到眼睛、鼻子和嘴巴那里。食物闻起来是什么味道？近距离观察的话，它看起来如何？在你把它放进嘴里之后，口感、纹理、温度如何？你不必“做”什么，你只需观察当时在起作用的不同的躯体感觉就可以了。

除躯体感觉之外，还请你留意心灵对食物做出的反应。比如，你的心灵对待这种食物的态度是喜欢，还是不喜欢？你是接受了食物原本的样子，还是对它的某些方面感到抗拒？你也许会觉得太烫或者太凉、太甜或者太酸。请你留意心灵如何忙着对食物进行评判，以及如何跟以前的饭菜做比较。

在吃了几口之后，你也许会发现，心灵开始对这种练习感到厌倦了，会游离开来，去想些别的事情。跟十分钟冥想一样，这是很正常的，没有什么可担心的。你要跟以前一样，一发现心灵游离开了，就温和地把注意力带回到冥想对象上来，即吃饭过程和食物的不同口感、味道、纹理、视觉，甚至咀嚼的声音。

随着你继续以这种方式进餐，你会开始注意到自己是否会习惯性地吃得很快，或者有偏好甜食的强烈冲动！也许你会注意到，你对自己正在吃的东西感到不安，尤其当你很注意自己的身材时。请你在这些不同的想法出现在心里的时候，留意它们，而且可以的话，请你同时留意吃饭的时候你的呼吸是怎样的。你的呼吸也许会告诉你，这个练习是否让你感到舒服。

当你快要吃完饭时，请你留意自己是否对快吃完饭有种失望感或者解脱感，甚至你可以再花些时间品味一下最后一口。

请你在起身离开或去吃下一样东西前，深呼吸几次，回想一下盘子里满是食物的
时候是什么样子，而现在里面空空如也的时候又是什么样子。请你比较一下之前
胃里的那种空荡感和现在的饱腹感。请你通过观察这些情况，留意不断变化和有
始有终的事物，留意心灵是如何随时间流逝而越来越自在的。

** 练习8：行走冥想

在开始行走之前，请你留意身体的感觉，你是感到沉重还是轻盈，僵硬还是放松？不要急着回答这个问题，你先花上几秒时间留意一下自己的姿势，留意一下自己的举手投足。

不要试图改变自己的行走方式，你只需要体察行走时的感受。跟呼吸一样，行走过程非常自动化、条件反射化，所以你甚至不需要思考。因此，你只需花一点时间去观察它、留意它。在这样做的时候，感到难为情是很正常的，但是这种感受通常会很快消失。

虽然你不需要对行走过程进行思考，然而你需要觉察周围发生的事情，因此，在你做这个练习的时候，请留意车辆、他人、交通信号灯等。

请你从留意周围发生的事情开始，可能是路人、商店的橱窗陈设、汽车、广告，以及其他在繁忙的城市里你可能会看到的一切。如果你住在郊区，那么你看到的更有可能是田野、树木，以及动物。请你留意事物的颜色、形状，观察事物的动态或静态。你不必真的去想自己看到了什么——你只管去看，只管承认它的存在就好。这个过程耗时30秒。

然后请你把注意力转向声音——你能听到什么？也许是你的脚踩到人行道上的声音，也许是路过的车辆的声音，也许是树上的鸟叫声或其他人走过的声音。

不要去想发出那种声音的事物，你只要花一点时间留意这些声音就好，就好像它们只是在你的觉醒之域来去。这个过程大约耗时30秒。

接下来，请你把注意力转向气味，花上大约30秒感受气味，有些气味可能令人愉快，但有些气味可能不那么令人愉快。你可能闻到花香或者须后水的味道，或者汽车尾气和汽油味，或者食物和饮料的气味，或者新修剪的草和其他植物的气味。请你留意心灵如何习惯性地围绕每种气味陷入无尽的思索，留意这种气味如何让你想起了某地、某物、某人。

最后，请你特别注意任何躯体感觉或者情感。也许你感受到温暖的阳光、凉爽的雨、嗖嗖的寒风，也许是每走一步脚跟触到地面时的感觉，也许是胳膊在身体两侧摆动时的感觉，甚至是紧张的肩膀或膝盖所带来的疼痛感。我们的目的仅仅是用大约30秒去留意这些感觉，不用觉得自己有必要对这些感受进行思考。

当你继续行走时，不要试图阻止这些想法进入你的觉醒之域——你只需要留意它们的来去，留意一件接一件的事物如何更迭替代。请你回想上文车辆与想法的类比，不同颜色的车辆从你身边来了又去，不同的想法在你的脑中来了又去。唯一的区别在于，你现在是在走着，而不是坐着。

一两分钟之后，请你温和地把注意力转到身体移动时的躯体感觉上来，留意重量如何节奏平稳地从右侧转到左侧，然后又转回到右侧。你需要尽量避免人为的速度调整，也尽量不要以特定的步伐行走（除非你在某个安静的地方，比如公园或者自己的家）。相反，请你观察自己已经习惯了的走路方式和节奏。也许由于做了这个练习，你将来会选择走得更慢一些。

把走路时的节奏、脚跟触到地面时的触感当作自己的觉醒起点，当作一个在意识到心灵游离之后可以从心理上回归的地方。请保持跟静坐冥想时一样的呼吸起伏感。

你不必专注到把外界一切都排除在注意力之外的地步。事实上，对周围发生的一切保持开放，然后在每次意识到心灵游离的时候，温和地将注意力带回到身体的动作和脚跟碰到地面时的触感上来。

现在，因为你更加心神俱在了，更加觉醒了，所以你的心理习惯（你惯常的思维方式）很可能也会变得更显而易见。通常情况下，我们极度沉浸于想法本身，以至于几乎注意不到我们对这些事物的反应。比如，当行走节奏被红灯打乱，被迫站住等一会儿才能继续走时，你是什么感受？你有没有感到不耐烦，有没有想要动起来继续前进的感觉？或者你可能会感到如释重负，想着终于有机会可以休息几秒了。

你也许会觉得，把这个技法拆分成好几个部分会很有帮助。比如，如果你需要从A处走到B处，而这段路程需要花费10～15分钟的时间，那么最好是一条街、一条街地做行走冥想。刚开始练习的时候，你要提醒自己走路的目的是要摆脱所有干扰，走到街道的尽头为止。一旦你意识到心灵游离了，就温和地把注意力带回到脚跟的触觉上来。当你到达街道尽头的时候，重新开始，就好像每次行走都是一个全新的练习一样。这样，你会觉得这个练习更好掌控一些。

如果你足够幸运，生活在公园、河流或者其他令人愉快的户外空间附近，那么在
这种环境下尝试这种技法也不错。在这些地方，外在的干扰会少很多，这会改变
行走冥想带给你的感受，还有助于你知道自己的心灵在这些截然不同的环境中会
有不同的作用方式。

** 练习9：跑步冥想

在你准备好去跑步之前，努力了解一下自己的感受。你的心里在想什么？你是感到焦虑、自信，还是完全无感？如果你有时间、有意愿，可以花上几分钟坐下来，在开始跑步之前让心灵安定下来。如果每次跑步前都这样做，你可能会开始注意到一种模式，这会帮助你更灵巧地做出回应。

在穿运动服的时候，你可以开始留意自己的躯体感觉。也许你的腿因为上一次跑步而感到有点沉重，或者你的肩膀因为坐在电脑前而感到紧张，或者通体有一种轻盈感。跟静坐冥想中的技法一样，在这样做的时候，请不要带任何评判或分析，只对自己的感受保持觉醒就可以了。

在出发之前，深呼吸几次会帮助你集中注意力，而且会给你带来与地面更强烈的接触感。用鼻子吸气，用嘴巴呼气。在开始跑之后，你可以使用任何你觉得最自然的呼吸方式。在出发之前，至少这样做4～5次。

在你开始跑的时候，要对周围发生的一切保持强烈觉醒，同时将注意力带回到身体上来。活动的时候你感觉如何？你的肌肉是如何对你的动作做出回应的？请你留意身体活动时呼吸的快速变化。如以前一样，在这个过程中除了对所有这些保持觉醒，其他没什么可做的。

你也要留意心灵是如何回应的。当你暂时“摆脱”了工作，走出了家门，伸展双腿并呼吸到新鲜空气时，你的心里有没有产生一种愉悦感？或者因为跑步后要做的辛苦工作，你感到了一种轻微的焦虑感？你脑中的各种想法又是怎样的呢？你的心灵是非常繁忙，不停地在想当天的所有事务，并开始思索明天要做的事务清单，还是非常安定，甚至因为身体的动作而感到欣慰？

随着你渐渐适应了跑步，你开始注意到稳定下来的节奏。这种节奏让你感到舒服吗？你的身体有什么感觉？你的身体是否感到协调？你的两条腿用力均匀吗？胳膊又有什么感觉？肩膀呢？身体中有没有哪个部位感到紧张？如果有，你知道该怎么做——留意它，观察它，对之保持觉醒，抵挡住那种想要摆脱它的欲望。你也许会发现，在觉醒的过程中，紧张感会自行消散。

如果你跑步是为了好玩，或者只是为了保持健康，那么积极地唤起对周围事物的觉醒会对你有所帮助。这些事物可能是其他跑步者、汽车、公园、田野、建筑乃至任何你途经的事物。很多时候，人们每天沿着同样的路线跑步，却对这条路线所知甚少，也几乎留意不到多少事物，这真令人惊讶。之所以这样，唯一的原因就在于向内的习惯，即陷在思索中的习惯。因此，请你保持适度的好奇心，不是要疯狂地努力留意周围的一切，而是要对吸引了你注意力的事物感兴趣。

因为你的心灵更有存在感、更加觉醒了，所以很可能你跑步时的思维方式（你的心理习惯）会变得更显而易见。你在跑步的时候有没有对自己特别严厉或和善的习惯？你的心灵会本能地飘到哪里，是向内进行思考，还是向外留意身体的感觉？你在跑步的时候是有一种强烈的自信感，还是感到难为情？所有这些都是你做这个练习的时候可以开始留意的东西。你还可以留意什么时候身体开始对跑步过程做出回应，什么时候身体开始释放内啡肽，什么时候开始感到所向无敌——好像你能够一直跑下去（条件是你在跑步中的某个阶段会出现这种情况）。

更觉醒带来的一个所谓的问题是，你不仅会觉察到令人愉快的感觉，而且会觉察到令人不快的感觉。然而，练习方式正确的话，即便令人不快的感觉也可以给人带来好的影响。因此，不要试图“摆脱”身体上的不适，而要看一看当你把注意力放在这种感受上时，会发生什么。这样做的时候试着把你和疼痛视为一体，因此你可以少想一些“我和我的疼痛”，而多想一些“疼痛”带来的简单而直接的体验。这样做可能会给你带来意想不到的结果。

无论是喘不上气、胸口发闷、大腿疼痛，还是小腿抽筋，所有这些都可以被用作有效的支持或者跑步冥想的时候注意力集中的对象。对于跑步冥想，在最初意识到疼痛的时候，人的本能反应是抗拒它、摆脱它，通常的做法是停下来，或者开始漫长的心理斗争，努力想强行克服它、忽视它或以某种方式压制它。当然，你需要了解自己身体的能力，尊重自己的身体，在必要的时候采取适当的措施。然而，如果你觉得自己可以在不造成任何持久伤害的情况下继续，那就离那种不适更近些，就好像你沉到那种感受中，并在以非常直接的方式去体验它一样。这种做法刚开始的时候可能有点违背本能，但是我们有实现这种疯狂的办法。在靠近它的时候，在充分感受它甚至是鼓励它的时候，我们常有的习惯性动态会发生完全的转变，而且很多时候，那种疼痛也会随之消失。

如果你跑步的态度十分认真，甚至带有竞争性质，那么你也许会更喜欢完全把注意力集中在跑步过程以及跑步的力学原理上。这个时候，有用而受欢迎的关注对象是脚踏在地上的感觉，这跟行走冥想中关注的对象相似。节奏感有时也会令人非常放松，它是一个很明显且很稳定的关注点。

无论你的关注对象是什么，请你尽量做到“少干涉”，尽量对这项锻炼保持放松的态度。就算你真的很努力想提高自己的跑步成绩，也要明白跑步真的不需要投入很多努力。虽然这话听起来有点奇怪，但是很多时候，你投入的努力越多，你就越紧张，然后你的速度会越慢。你甚至可以把这当成自己跑步过程中关注的对象，密切观察自己在跑步中投入了多少努力，然后留意这种做法反过来对你的步幅有什么样的影响。

无论你只是为了玩乐还是认真跑步，如果你把跑步里程拆分成几个部分，你会发现一切会更可控。有些人发现按每步进行分程是最佳的关注方式，而有些人发现按每条街、每千米进行分程的关注方式最好。一种很受欢迎的方式是将跑步里程拆分成每10步、每20步，或者每100步。这种做法有点像数自己的呼吸，它有助于我们阻止心灵游离。很显然，你打算关注的距离越长，你就越难记住这些原则，因此你要经常查看，特别留意在跑步过程中心灵是否在场。

** 练习10：睡眠冥想

在你上床睡觉之前，确保去过了厕所、锁上了门、关掉了手机，并做了你平常上床睡觉之前会做的一切事情。你甚至可以为第二天早上做一些准备，或者为第二天要做的事情列个清单。

为上床做好准备之后，盖上被子，平躺在那里，就好像要睡觉了一样。为了更舒服，你可以在头下方放一个薄枕头。如果你平常习惯趴着睡或者侧着睡，没关系，这个练习最好是躺着进行，做完之后可以再翻回去睡觉。躺在那里的时候，你需花一点时间体察陷进床里的感觉，体察身体被床支撑着的感觉，体察这一天到头再也没有什么事情要做了的感觉。

躺舒服之后，你需做5次深呼吸，用鼻子吸气，嘴巴呼气，就像在十分钟冥想中所做的那样。在吸气的时候，你需努力感受肺部充满空气、胸腔扩张的感觉。呼气的时候，你可以想象一下：当天的想法和感受都消失得无影无踪，身体中的紧张感也都消散了。这有助于你的身体和心灵为要进行的练习做好准备。

第一步： 从“签到”开始，按平常的方式，你要留意自己的感受，包括身体的感受和心灵的感受。记住，就跟放松时不可匆忙一样，睡觉也是不可匆忙的，因此，当你做这个练习中的这一部分时，要慢慢来。如果你有许多想法在打转（这绝对是很正常的），不要担心，暂时由着它们去。无论做什么，请你不要被诱惑着抗拒那些想法，无论这些想法多么令人不安或者不舒服。

接下来，你要更仔细地留意身体与床的接触点。请你将注意力带回到身体与床接触时的那种感觉上，留意身体陷进床里的感觉，注意那个接触感最强烈的部位——你的身体重量分布均匀吗？你还可以注意任何声音或其他感觉。在你想要睡觉的时候，声音有时候特别令人困扰。在刚开始的时候，你要辨认一下那种声音究竟是你可以改变的，还是你左右不了的、一点办法都没有的，这样做会有一些作用。然后，你不要抗拒那种声音，只要温和地把注意力集中在声音上，保持大约30秒，然后再把注意力带回到自己的身体上来。

现在，请你努力了解身体的切实感受。在刚开始的时候，你可以在大体上去感受。比如，身体是感到沉重还是轻盈，是不安还是安静？然后，你需更精确地用心灵对身体进行扫描，从头顶到脚趾，温和地体察任何紧张感。你的注意力会不可避免地被吸引到紧张的部位，但是要知道，你快要睡觉了，而这个练习会缓解这些紧张，你大可以放松下来。你可以多扫描几遍，每次花上大约30秒的时间。记住，你不光要留意令你不适的部位，而且要留意那些感到放松和舒适的部位。

到现在为止，你很可能已经留意到了呼吸带来的起伏感，但是如果还没有，请你把注意力带到能够更清楚地感受到这种起伏的部位。跟往常一样，不要试图以任何方式改变呼吸的节奏，相反，让身体顺其自然。跟十分钟冥想一样，在睡眠冥想的练习中，呼吸方式没有正确或错误之分。因此，如果你的胸腔部位起伏更明显，而腹部起伏不明显，你也不要担心。你需留意呼吸是深还是浅，是长还是短，是顺畅还是不规律。这并不要求你做任何努力。你需要做的不过是留意身体的活动而已。

如果呼吸非常浅、很难察觉，你可以把手放在你觉得活动最强烈的部位，这样做也许会有些帮助。在把手放在那里之后，随着手来回移动追踪呼吸的起伏。

在对呼吸进行了1～2分钟的观察之后，你的心灵会游离开来，这是很正常的。在你意识到分心和心灵游离的时候，你的心灵其实就已经回来了，你需要做的就是，温和地把注意力重新带回到身体的起伏上来。你不需要对这部分练习进行计时，当你觉得已经过了1～2分钟的时候，自然地进入下一部分。

第二步： 这一步是以专注的、有条理的方式回顾这一天。从这一天中你所能记得的第一个时间点开始，从早上醒来之后开始。你还记得醒来时的心情吗？现在，就好像你的大脑被设定了非常温和的“快进”一样，在心灵重放一天中经历的事件、会面、对话的时候，你在静静观察。这并不需要进行得多详细，更多的只是个概览，是一系列在心灵中闪过的快镜头。

比如，你在脑中回想自己翻身下床，关掉闹铃，走到浴室，冲澡，吃早餐，进行冥想，步行去工作，跟同事打招呼等。你可以花大约3分钟的时间来浏览这一天，一直回顾到此刻为止。这么多事情，要在几分钟之内做完，好像很难办到，但这只是对这一天进行的概览，因此，不要超过3分钟或者4分钟。过几天之后，你一定会对这个速度感到自在。

在心灵回放这一天的情况时，你会不可避免地有一种冲动，即陷入沉思。也许你想到了白天那场进展很顺利的会议，然后你开始想其中存在的所有可能。也许你想起了自己跟上司之间的争吵，你开始担忧这个争论所带来的影响。最初的时候，心灵像这样游离是很正常的，但是很明显，都到了夜间这个时间点了，再去想新的东西已经无益了。因此，像以前一样，当你意识到自己分心的时候，温和地回到正在你心灵中回放的这部“电影”上来，从离开的地方重新开始。

第三步： 在把自己带回到此刻之后，现在你可以把注意力带回到身体上来。你要把注意力放到左脚的小脚趾上，想象着要睡觉了，把它“关掉”。你甚至可以在集中注意力的时候，在自己的心里重复“关掉”或“休息”这样的字眼。这种做法就好像你在向肌肉、关节、骨头以及其他身体部位发出许可，准许它们关掉去休息，你知道直到第二天早上之前，你将不会再需要它们。然后你要对第二个脚趾做同样的事情，然后第三个脚趾……以这种方式继续，从脚掌、足弓、脚跟、脚踝、小腿等，然后一路往上，到臀部，到骨盆部位。

在对右腿重复这个练习之前，你要花一点时间感觉一下已经“关掉”的那条腿和还没被“关掉”的那条腿之间的区别。如果你在做这个练习的时候，对到底有没有发生什么有所怀疑，那时你就会感觉到区别。你需对右腿重复这个练习，再一次从脚趾开始，一路向上直到腰部那里。

请你继续这个练习，往上到躯干，然后向下到胳膊、手和手指，然后再向上到喉咙、脖子、脸以及头顶。你要花一点时间享受摆脱了紧张后的感觉，享受不需要对身体做任何事情的感觉，享受放弃了对身体的控制后的感觉。现在，请你任由心灵随心所欲地游荡，任由它自由地从一个想法联想到下一个，无论它想去哪里都行，直到迷迷糊糊地睡去。

任选附加： 当你完成上述步骤时，你很可能已经沉沉睡着了。如果睡着了，那么请你享一夜安眠，好好睡觉。如果没睡着，你也不要担心——这并不说明你做这个练习的方式不对。记住，这个练习本来的目的就不是催眠，而是增强你在夜间的觉醒意识，增进你对心灵的夜间情况的理解。

因此，如果你还醒着，还有两种方法可行。第一种方法是任由心灵漫无目的地游离，任由它以平常的方式随心所欲地联想，不施加任何控制，不施加任何强迫。这种做法有时候感觉好像不错，但是唯一的问题在于，有些人会觉得这有点儿含糊，甚至有点儿令人不安。如果你就是这种情况，那么以这个练习的第二步作为结束，对你可能更为有用。

第二种方法是从1000往0倒数。这听起来好像是一项不可能完成的任务，感觉好像特别难。如果以正确的方式去做，这其实根本不需要你付出任何努力。在从清醒向睡眠转变的过程中，这是一种很好地使心灵保持专注的方法。跟以前一样，心灵游离是很正常的，因此，当你意识到自己走神了的时候，只需温和地回到你中断的那个数字，然后从那里继续。

最后我再指出一点，在做这个练习的时候，你要真诚地想要数到0，这一点很重要。不要把这当成一种入睡方式，而是把它视为一个在身体和心灵准备“关掉”去休息前使你保持忙碌和专注的练习。无论心灵中出现了什么样的想法，无论这些想法是关于入睡的还是别的事情，请任由它们来去。你唯一的目的、你唯一的关注焦点是努力从1000倒数到0。如果你在倒数的中途迷迷糊糊睡着了，那也没关系。


* Footnotes


