baseURL = "https://dreamanddead.github.io"
disablePathToLower = true
languageCode = "zh-cn"
title = "时长N年半"
theme = "diary"
copyright = "DreamAndDead 2014-2021"
googleAnalytics = "UA-93899485-1"

# aliyun oss
cloud_url = "https://dreamanddead-github-io.oss-cn-hongkong.aliyuncs.com"

# ignore emacs cache file when rendering
ignoreFiles = ["d@d-pc.*"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "关于技术，系统，智能"
enableReadingTime=true
disableAutoCollapse=true
disqusShortname = "dreamanddead"


# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
# will set 'og:site_name'
title = "时长N年半"
# will set 'og:description'
description = "关于技术，系统，智能"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[[menu.main]]
url = "/series"
name = "系列"
weight = 2

[[menu.main]]
url = "/categories"
name = "分类"
weight = 3

[[menu.main]]
url = "/tags"
name = "标签"
weight = 4

[[menu.main]]
url = "/index.xml"
name = "订阅"
weight = 5

