# baseURL = "https://dreamanddead.github.io"
baseURL = "http://localhost:8000"
disablePathToLower = true
languageCode = "zh-cn"
title = "Brain=f(X)?"
theme = "diary"

[params]
enableReadingTime=true
disableAutoCollapse=true

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4

