baseURL = "https://dreamanddead.github.io"
disablePathToLower = true
languageCode = "zh-cn"
title = "Brain=f(X)?"
theme = "diary"

[params]
enableReadingTime=true
disableAutoCollapse=true
enableGitalk=true

[params.gitalk]
owner="DreamAndDead"
repo="blog"
client_id="a62107312fece4c4dcb1"
client_secret="d7dbf28c47e28300664972e82b89b244c40e40c3"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4

