#+setupfile: ../setup.org

#+hugo_bundle: algo-basic-enum-perm
#+export_file_name: index

#+title: 基础算法之枚举 排列 组合
#+date: <2021-03-25 四 15:10>
#+hugo_categories: Algorithm
#+hugo_tags: algorithm programing
#+hugo_draft: true
#+hugo_custom_front_matter: :comment false :featured_image images/featured.jpg 

暴力是第一尝试法

枚举出所有情况，一一检测

- 检验思路
- 小规模数据集
- 对复杂度有所了解
- 过度优化
- hand on dirty
- 继续改进
  
枚举排列 组合是常见的情况

单独讲解

* 集合

排列与组合都涉及到一组元素，称这组元素为集合（set）。
排列是集合所有元素的一种顺序；
组合是集合的子集。

存在一种集合的推广，称为多重集合（multiset）[fn:1]。
在一个集合（set）中，相同的元素只能出现一次；
在多重集（multiset）之中，同一个元素可以出现多次。

集合类别不同，枚举的方法也存在些许差异。

* 排列

排列是集合中所有元素对应的一个有序序列。

有两种常用方式来枚举排列，迭代法和递归法。

** 迭代法

迭代法和字典序相关。

字典序，义如其名，如字典中单词一样的排序规则，
- 两个单词（序列）从左到右，依次比较字符（元素），直到比出大小
- 空字符（元素）最大

考虑集合 ={1, 2, 3, 4}= ，存在 16 个排列序列。

将所有序列按照字典序从小到大排序，
其中相邻的两个序列有明显的关系，
迭代法枚举排列利用的就是这一点。

#+begin_example
1 2 3 4
1 2 4 3
1 3 2 4
1 3 4 2
1 4 2 3
1 4 3 2
2 1 3 4
2 1 4 3
2 3 1 4
2 3 4 1
2 4 1 3
2 4 3 1
3 1 2 4
3 1 4 2
3 2 1 4
3 2 4 1
3 4 1 2
3 4 2 1
4 1 2 3
4 1 3 2
4 2 1 3
4 2 3 1
4 3 1 2
4 3 2 1
#+end_example

第一个最小的序列是已知的，将元素排序即可， =1 2 3 4= 。
然后不断枚举字典序中相邻的下一个序列。

如何找出下一个序列？

根据字典序的定义，左边的元素影响大于右边的元素。
在寻找相邻的下一个序列时，从尾部开始变动，尽量不变动头部的元素。

以序列 =1 2 3 4= 为例，
- 最后一位为 4，只有一个数，没有变动的空间，跳过
- 最后两位为 =3 4= ，因为 =3 < 4= ，则可以交换两者，得到下一个字典序 =1 2 4 3=

以序列 =1 2 4 3= 为例，
- 最后一位，跳过
- 最后两位， =4 3= ， =4 > 3= ，已经没有可调整的空间，使字典序变大，只能继续向前
- 最后三位， =2 4 3= ，此时 =2 < 4= ，但是不能直接交换 2 4，交换 2 3 是更好的选择，
  因为在最后两位中， 3 是比 2 大的最小的数，而不是 4。
  高位确定之后，得到 =1 3 4 2= ，
  这个序列虽然比 =1 2 4 3= 大，但不是最小的，
  此时需要将低两位排序，得到比 =1 2 4 3= 大的最小的字典序 =1 3 2 4= ，即与之相邻。

#+begin_quote
练习：考虑 =2 4 3 1= 到 =3 1 2 4= 的过程
#+end_quote

上面只是从语言层面描述了算法的过程，进一步明确两个问题

*如何寻找替换高位的最小元素？*

在不得已替换高位时，可以发现，高位后的低位问题逆序排列的情况。
如果不是逆序，说明存在不需要替换高位的更大的字典序。

=1 4 3 2= 需要替换 高位 1，但是 =1 4 2 3= 就不需要替换高位。

所以只需要倒序依次查找，直到找到比高位大的最小元素即可。

*替换高位后，所有低位必须要进行 sort 过程？*

仔细考虑其实不需要，因为低位已经是逆序，交换高位后，逆序的性质并没有改变。
此时只需要 reverse[fn:2] 低位，就可以得到低位的排序。

#+begin_src c++ -n 1
bool next_perm(int perm[], int n) {
  for (int i = n-1; i > 0; i--) {
    int j = i - 1;

    if (perm[i] > perm[j]) {
      int k;
      for (k = n-1; k >= i; k--) {
        if (perm[k] > perm[j])
          break;
      }

      swap(perm[j], perm[k]);

      reverse(perm + i, perm + n);

      return true;
    }
  }

  return false;
}
#+end_src

考虑多重集合 ={1, 2, 2, 3, 3, 3, 4}= ，上述算法过程是否生效？

例如 =2 4 3 3 3 2 1= ，应用上述代码过程，
可能观察到算法依然是有效的，

#+begin_example
locate
2 4 3 3 3 2 1
j i     k

swap
3 4 3 3 2 2 1
j i     k

reverse
3 1 2 2 3 3 4
j i     k
#+end_example

关键在于两处，
j i 比较使用 >，而非 >=
j k 比较使用了 >，而非 >=

过程本身处理了可重集合的情况。


有一个好消息，标准库已经实现了这个方法， ~std::next_permutation~ ，
同时对可重集生效。

| 题目   | 标题     | 难度 | 启发                                   |
|--------+----------+------+----------------------------------------|
| uva146 | ID Codes |    1 | next_perm 的实现原理 |

** 递归生成

另一种是递归生成的方式

考虑集合 ={1, 2, 3, 4}=

每次递归，从左到右，依次确定一个元素的位置，直到没有元素可以摆放。

确定元素位置时，从小到大遍历，检测是否已经出现过

这样满足字典序的输出方式。

TODO e.g. code

对于可重集，相同的过程不生效

比如 ={1, 1, 1}= ，代入上面的算法，会生成 8 遍 =1 1 1= 的排列，
显然是重复的。

在每次确定元素的时，只遍历元素的种类，而不是全部遍历

比如 ={1, 1, 2, 2, 3, 4}= ，只遍历 =1 2 3 4= 即可

同时在确定是否可以摆放时，要计算元素是否已经使用完，而不是是否出现过，
因为元素可能是多个

可认为是前面一种算法的拓展情况

TODO e.g. code

| 题目     | 标题               | 难度 | 启发                                                        |
|----------+--------------------+------+-------------------------------------------------------------|
| uva10098 | Generating Fast    |    1 | 递归生成可重集                                                     |
| uva524   | Prime Ring Problem |    1 | 掌握递归生成 perm 的方法，就可以提前利用 prime 条件进行剪枝 |

* 组合

组合和子集之间有明确的一一对应的关系，
组合就是从全部元素中挑选出部分元素的集合。

同样的，枚举组合有迭代和递归两种方式。

区别是，下面的算法只面向普通集合，不考虑可重集合的情况。

** 迭代

组合，就是从全部元素中挑选中部分元素的集合，即子集。

如果用 1 表示元素存在， 0 表示元素不存在，那一个二进制数
就可以唯一确定一个组合。

比如集合 ={1, 2, 3, 4, 7, 9}= 的子集，

#+begin_example
{ 1, 2, 3, 4, 7, 9 }
0b1  1  1  1  1  1

{ 1,    3, 4, 7, 9 }
0b1  0  1  1  1  1

{ 1, 2,       7, 9 }
0b1  1  0  0  1  1

{                  }
0b0  0  0  0  0  0
#+end_example

全集全部为 1，空集为 0，其它子集在两者之间。

这样就是将集合和整数一一对应起来，
n 个元素的集合，共有 2^n 个子集。

这就是迭代方式的原因，整数从 0 到 2^n，根据位情况，决定集合。


TODO 不是字典序？

使用这种对应方法还有另外的好处，二进制运算和集合运算关联起来。

与 集合的交
或 集合的并
异或 集合的减，如果是包含，
     集合的除与的剩下的部分，


这种表示法，另外的 trick。

一种子集分割的方法。

上面是全集分割子集的方法，可以从 0 开始遍历

假如已经分割出子集，比如 0b010011 ，
枚举这个子集中的子集，依然使用同样的表示法？


1. 继续从 0 到 2^n，判断是否为其子集，效率不高

2. left right 的分割法

从上向下减


另一个 trick，如何枚举只有 k 个元素的集合。
结合上面，


有 n 个元素的集合，用长度为 n 的数组 0001111111，不用二进制数，而使用相同的原理，
k 个 1 在低位，

使用 next perm 方法，可得到所有排列方式，即子集的选择方式


** 递归方式

有两种方式

一种是定序，后面的元素必须比前面大，才可以加进去

不需要遍历到长度结束

另一种，每次递归，针对第 ith 个元素，可选择用还是不用，
最终到长度结束，再确定集合。

* 题目

https://www.luogu.com.cn/training/108#information

| 题目        | 标题 | 难度 | 启发 |
|-------------+------+------+------|
| luogu P1036 |      |      |      |
| luogu P1157 |      |      |      |

* 如何选择

迭代 / 递归

迭代必定超时，剪枝，

检验过程是递进的


迭代，并检验

  
* 解答树

将递归枚举的模式统一起来

并归纳复杂度


[fn:1]: https://baike.baidu.com/item/%E5%A4%9A%E9%87%8D%E9%9B%86

[fn:2]: https://blog.csdn.net/u011465808/article/details/37886527
